---
title: "Calculators"
author: "Chris Marston"
date: "2/14/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
TEST CHANGE
## Calculators

**Other**
``` {r}
# Total number of outcomes:
  # Multiply the number of outcomes for each event together (RedBook p12)
# "Digits" are any numerals from 0 to 9. That is, 0 through 9 are all digits.
```

**Expected Value**
``` {r}

E_of_X = function(probs, vals) {
  return(sum(vals*probs))
}

Var_of_X = function(probs, vals) {
  return(sum((vals^2)*probs) - (E_of_X(probs, vals)^2))
}

Std_of_X = function(probs, vals) {
  return(sqrt(Var_of_X(probs, vals)))
}

probs1 = c(12/52, 40/52)
vals1 = c(30, -2)
probs2 = c(1/6)
vals2 = c(1:6)
probs3 = c(0.3, 0.25, 0.15, 0.05, 0.10, 0.15)
vals3 = c(1:6)

# Expected value of 1
E_of_X(probs1, vals1)

# Variance of 1
Var_of_X(probs1, vals1)

# Standard Deviation of 1
Std_of_X(probs1, vals1)

# Expected value of 2
E_of_X(probs2, vals2)

# Variance of 2
Var_of_X(probs2, vals2)

# Standard Deviation of 2
Std_of_X(probs2, vals2)

# Expected value of 3
E_of_X(probs3, vals3)

# Variance of 3
Var_of_X(probs3, vals3)

# Standard Deviation of 3
Std_of_X(probs3, vals3)


```

**Bernoulli Distribution**
``` {r}


```

**Binomial Distribution**
``` {r}
probOfSuccess = 0.15 # Probability of getting a question correct, etc.
probSize = 10 # Total number of questions answered, etc.
numTrials = 1 # Number of questions answered correctly, etc.

# Success on less than numOfTrials
LTNumTrials = c(0 : numTrials - 1)
sum(dbinom(LTNumTrials, probSize, probOfSuccess))

# Success on numTrials or less
LEQNumTrials = c(0 : numTrials)
sum(dbinom(LEQNumTrials, probSize, probOfSuccess))

# Success on exactly numOfTrials
dbinom(numTrials, probSize, probOfSuccess)

# Success on numOfTrials or more
GEQNumTrials = c(numTrials : probSize)
sum(dbinom(GEQNumTrials, probSize, probOfSuccess))

# Success on greater than numOfTrials
GTNumTrials = c(numTrials + 1 : probSize)
sum(dbinom(GTNumTrials, probSize, probOfSuccess))

```






